sonar.projectKey=duyp6090_Yummy-Website-Order-Food
sonar.projectName=Yummy Website Order Food
sonar.organization=duyp6090
sonar.sources=.
sonar.exclusions=**/node_modules/**
sonar.language=javascript
